export const dashboardContent = {
  brand: "Nocta",
  sidebar: {
    eyebrow: "Nightly focus",
    navLabel: "Navigate",
    workspaceLabel: "Workspace",
    profileLabel: "Signed in",
    tagline: "One action",
    taglineSupport: "Close the night with clarity.",
  },
  nav: {
    tonight: "Tonight",
    goals: "Goals",
    reflect: "Reflect",
    activity: "Platform activity",
  },
  greeting: {
    morning: "Good morning",
    afternoon: "Good afternoon",
    evening: "Good evening",
    night: "Still up?",
    /** Toast / legacy two-part welcome. Navbar uses navbarGreeting(). */
    welcome: (name: string) => `Welcome back, ${name}`,
    fallbackName: "there",
  },
  actions: {
    platformCommits: "Platform activity",
    backToDashboard: "Dashboard",
    logout: "Log out",
    openSidebar: "Open sidebar",
    closeSidebar: "Close sidebar",
    themeLight: "Switch to light mode",
    themeDark: "Switch to dark mode",
    themeLightShort: "Light mode",
    themeDarkShort: "Dark mode",
  },
  tonight: {
    windowTitle: "Nocta · Tonight",
    eyebrow: "Tonight",
    title: "One next step",
    body: "Your scored action for the night will show up here.",
    emptyCta: "Add goals to begin",
  },
  pulse: {
    windowTitle: "Nocta · Week",
    eyebrow: "Week",
    title: "No pulse yet",
    body: "Streaks appear once you start logging nights.",
  },
  tip: {
    windowTitle: "Nocta · Note",
    eyebrow: "Note",
    title: "Rest counts",
    body: "A recovery night is still a valid priority.",
  },
};
