export const dashboardContent = {
  brand: "Nocta",
  navbar: {
    dashboard: "Dashboard",
    activity: "Platform Activity",
    searchPlaceholder: "Search",
    searchHint: "⌘K",
  },
  sidebar: {
    planLabel: "Plan",
    workspaceLabel: "Workspace",
    profileLabel: "Signed in",
    signedOutLabel: "Not signed in",
    profileLoading: "…",
    tagline: "One action",
    taglineSupport: "One clear next step.",
  },
  nav: {
    dashboard: "Dashboard",
    goals: "Goals",
    reflect: "Reflect",
    activity: "Platform activity",
  },
  greeting: {
    morning: "Good morning",
    afternoon: "Good afternoon",
    evening: "Good evening",
    night: "Still up?",
    /** Toast / legacy two-part welcome. Home card uses navbarGreeting(). */
    welcome: (name: string) => `Welcome back, ${name}`,
    fallbackName: "Random User",
    emptySupport: "Add a goal when you’re ready. Rest is part of the model.",
    supportWithMomentum:
      "Momentum holds when you rest. One clear step when you don’t.",
  },
  actions: {
    platformCommits: "Activity",
    backToDashboard: "Dashboard",
    logout: "Log out",
    openSidebar: "Open sidebar",
    closeSidebar: "Close sidebar",
    pinSidebar: "Keep sidebar open",
    themeLight: "Switch to light mode",
    themeDark: "Switch to dark mode",
    themeLightShort: "Light mode",
    themeDarkShort: "Dark mode",
    browseActivity: "Activity",
    addGoals: "Add goals",
    continueTonight: "Continue",
  },
  account: {
    menuLabel: "Account menu",
    sheetTitle: "Account",
    theme: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    themeLightHint: "Always light",
    themeDarkHint: "Always dark",
    themeSystemHint: "Match system",
  },
  stats: {
    momentum: "Momentum",
    goals: "Goals",
    nights: "Sessions logged",
    recovery: "Recovery",
  },
  continue: {
    eyebrow: "Continue where you left off",
    emptyTitle: "Nothing queued yet",
    emptyBody:
      "When goals and a check-in are in place, your one next step shows up here.",
    meta: "Scored pick · Add goals to begin",
  },
  checkIn: {
    title: "Check in",
    body: "Two answers. Then one clear next step.",
    timeLabel: "How much time?",
    energyLabel: "How’s your energy?",
    minutes: [
      { id: 20 as const, label: "20 min", hint: "Small step" },
      { id: 45 as const, label: "45 min", hint: "Focused block" },
      { id: 90 as const, label: "90+ min", hint: "Longer stretch" },
    ],
    energy: [
      { id: "low" as const, label: "Low", hint: "Keep it light" },
      { id: "steady" as const, label: "Steady", hint: "Ready to work" },
      { id: "high" as const, label: "High", hint: "Plenty left" },
    ],
    submit: "Find my next step",
    submitHint: "Nothing is suggested until you continue.",
    submitLoading: "Finding your next step…",
    restoreLoading: "Loading check-in…",
    adjust: "Adjust",
    pickLabel: "Your next step",
    scoreLabel: "Score",
    whyLabel: "Why this",
    alsoScored: "Also scored",
    toastSuccess: "Here’s your next step",
    toastAdjust: "Check-in cleared",
    toastError: "Couldn’t check in. Try again.",
    emptyGoalsTitle: "Add a goal first",
    emptyGoalsBody: "Check-in needs at least one active goal to rank.",
    emptyGoalsCta: "Go to Goals",
    /** Labels for building the “Why this” line from ScoringFactors. */
    factorLabels: {
      deadline: "Deadline",
      neglect: "Neglect",
      weight: "Weight",
      momentum: "Momentum",
    },
    todaySummary: (timeLabel: string, energyLabel: string) =>
      `${timeLabel} · ${energyLabel}`,
  },
  today: {
    title: "Today",
    plannerLabel: "Check-in",
    plannerEmpty: "No check-in yet today.",
    planLabel: "Week",
    planEmptyTitle: "No pulse yet",
    planEmptyBody: "Momentum and sessions appear once you start logging.",
    tip: "Recovery doesn’t cost you momentum.",
  },
};

export type CheckInMinutes = (typeof dashboardContent.checkIn.minutes)[number]["id"];
export type CheckInEnergy = (typeof dashboardContent.checkIn.energy)[number]["id"];
