export const dashboardContent = {
  brand: "Nocta",
  sidebar: {
    eyebrow: "Nightly focus",
    navLabel: "Navigate",
    workspaceLabel: "Workspace",
    profileLabel: "Signed in",
    tagline: "One meaningful action",
    taglineSupport: "Score what matters. Close the night with clarity.",
  },
  nav: {
    tonight: "Tonight",
    goals: "Goals",
    reflect: "Reflect",
    activity: "Platform activity",
  },
  greeting: {
    morning: "Good morning",
    afternoon: "Good afternoon",
    evening: "Good evening",
    night: "Still up?",
    welcome: (name: string) => `Welcome back, ${name}.`,
    fallbackName: "there",
  },
  actions: {
    platformCommits: "Platform activity",
    backToDashboard: "Dashboard",
    logout: "Log out",
    openSidebar: "Open sidebar",
    closeSidebar: "Close sidebar",
    themeLight: "Switch to light mode",
    themeDark: "Switch to dark mode",
    themeLightShort: "Light mode",
    themeDarkShort: "Dark mode",
  },
  tonight: {
    windowTitle: "Nocta · Tonight",
    eyebrow: "Tonight",
    title: "One next step",
    body: "When your goals are in, Nocta will score them and pick a single action for the night.",
    emptyCta: "Goals come next",
  },
  pulse: {
    windowTitle: "Nocta · This week",
    eyebrow: "This week",
    title: "Quiet for now",
    body: "Streaks and neglected areas will show up here when goals are live.",
  },
  tip: {
    windowTitle: "Nocta · Note",
    eyebrow: "Remember",
    title: "Rest counts",
    body: "A recovery night is a valid priority. Keep the UI calm when the score says so.",
  },
};
